[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  PYTHON_VERSION = "3.11"
  VITE_BACKEND_URL = "https://dietary-delight.onrender.com"
  MISE_DISABLE = "1"
  VITE_RECIPE_LIMIT = "10000"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for API calls
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization" 