[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
numReplicas = 1

# Environment variables
[deploy.variables]
CHROMA_DB_PATH = "/app/data/chroma_db"
RAILWAY_ENVIRONMENT = "true"

# Persistent volume for ChromaDB data
[[volumes]]
mountPath = "/app/data"
